In [1]:
#data and visuals
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
bain = pd.read_csv("../raw/bain_training_set_raw.csv")
bain.columns = bain.columns.str.replace("vv_bain_acxiom_match_data.", "", 1)
bain.head()

,surveygroupid,surveyid,sitename,surveydate,userhostaddress,redflag,scored,q126_gender,q127_age,q131_country_of_residence,...,shoppingandpurchasechannel_onlinepurchaseindicator,client_id,crm_id,c360_id,dob,country,seaware_id,master_id,vxp_id,data_loaded_from_nl
0,495554,4269555,Virgin Voyages,23:49.4,71.215.49.237:55524,0,1,Male,62,United States,...,True,8621,0016A00000m8KcQQAU,4.050200e+18,NaN,US,7976,e328617a-ae8e-4195-bf04-6deaf83d23c1,ND in XREF Master,N
1,494177,4267920,Virgin Voyages,06:37.3,107.77.202.190:54560,0,1,Female,50,United States,...,True,11459,0016A00000m8KjFQAU,3.559360e+18,NaN,US,8737,7aef19a0-d591-487d-a6b7-ff40b40cd1fc,ND in XREF Master,N
2,495191,4269082,Virgin Voyages,45:02.0,47.133.71.255:48704,0,1,Male,58,United States,...,True,2029,0016A00000nPizwQAC,3.775250e+18,NaN,US,10736,2e54f7a8-41ca-484a-97fe-2ee7da488a6f,ND in XREF Master,N
3,494586,4268355,Virgin Voyages,15:15.0,67.85.162.213:48450,0,1,Female,45,United States,...,True,44406,0016A00000nQOCxQAO,7.233730e+18,NaN,US,12235,ba1bf92d-767d-4945-9335-80b3c1665bb2,14dd85a8-01f3-4965-866e-66a1b5e2b256,N
4,494841,4268636,Virgin Voyages,57:13.7,107.77.204.42:14323,0,1,Female,36,United States,...,False,23280,0016A00000nQYJHQA4,7.292790e+18,NaN,US,13087,ce06a040-19cb-454e-8ddc-7dfa30a286d4,ND in XREF Master,N

dtype('O')

In [131]:
for i in bain.columns:#[col for col in bain.columns if 'acxiom' in col]:
    if bain[i].dtypes != bain['sitename'].dtypes:
        print(i)

surveygroupid
surveyid
redflag
scored
q100
q101
q102
q103
q104
q105
q106
q107
q108
q109
group
person_basicdemographics_age
person_basicdemographics_deceased
person_basicdemographics_enteringadulthood
person_basicdemographics_lengthofresidence
person_basicdemographics_singleparent
household_basicdemographics_africanamericanprofessionals
household_basicdemographics_childnearhsgraduation
household_basicdemographics_childrenpresent
household_basicdemographics_estimatedincomemin
household_basicdemographics_estimatedincomemax
household_basicdemographics_generations
household_basicdemographics_lengthofresidence
household_basicdemographics_newmover
household_basicdemographics_newlywed
household_basicdemographics_numberofadults
household_basicdemographics_numberofchildren
household_basicdemographics_numberofpeople
household_basicdemographics_probableteendriver_reacheddrivingage
household_basicdemographics_probableteendriver_withinoneyearofdrivingage
household_basicdemographics_recentcollegegraduate
household_basicdemographics_recentdivorce
household_basicdemographics_senioradultinhousehold
household_basicdemographics_singleparent
household_basicdemographics_sohoindicator
household_basicdemographics_veteran
household_basicdemographics_workingwoman
household_basicdemographics_youngadult
household_basicdemographics_youngadultinhousehold
causesandvolunteer_communitycharities
causesandvolunteer_environmentalissues
causesandvolunteer_donation
political_currentaffairsandpolitics
spending_averagedaysbetweenonlineorders
spending_averagedollaramountperorder
spending_averagedollaramountperpurchase
spending_categoryspend_apparel
spending_categoryspend_artsandantiques
spending_categoryspend_automotive
spending_categoryspend_beauty
spending_categoryspend_books
spending_categoryspend_childrensproducts
spending_categoryspend_collectibles
spending_categoryspend_computinghomeoffice
spending_categoryspend_craftshobbies
spending_categoryspend_electronics
spending_categoryspend_foodandbeverage
spending_categoryspend_furniture
spending_categoryspend_garden
spending_categoryspend_generalmerchandise
spending_categoryspend_gifts
spending_categoryspend_health
spending_categoryspend_holidayitems
spending_categoryspend_homecare
spending_categoryspend_homefurnishings
spending_categoryspend_housewares
spending_categoryspend_jewelry
spending_categoryspend_linens
spending_categoryspend_music
spending_categoryspend_novelty
spending_categoryspend_other
spending_categoryspend_personalcare
spending_categoryspend_pets
spending_categoryspend_photoandvideo
spending_categoryspend_specialtyfood
spending_categoryspend_specialtygifts
spending_categoryspend_sportsandleisure
spending_categoryspend_stationery
spending_categoryspend_travel
spending_categoryspend_videosanddvds
spending_firstonlinepurchasedate
spending_lastonlinepurchasedate
spending_offlinedollars
spending_onlinedollars
spending_onlineorders
spending_retailactivitydate
spending_retailrecentpurchases_retailactivitydate
spending_travelspendmin
spending_travelspendmax
spending_totalonlinedollars
spending_totalonlineorder_dollars1000plus
spending_totalonlineorder_dollars100to250
spending_totalonlineorder_dollars250to500
spending_totalonlineorder_dollars500to1000
spending_totalonlineorder_dollars50to100
spending_totalonlineorder_dollarsunder50
spending_totalonlineorder_total
spending_weekssincefirstonlineorder
spending_weekssincelastonlineorder
tobacco_smokingtobacco
etechdemographics_assimilationindex
alcohol_wineinterest
mediaconsumption_mailorderresponder
mediaconsumption_textmessaging
marketindicespopulationdemographicsage_age18plus_averageage
marketindicespopulationdemographicsage_age18plus_medianage
marketindicespopulationdemographicsage_age18plus_percentage18to24
marketindicespopulationdemographicsage_age18plus_percentage25to34
marketindicespopulationdemographicsage_age18plus_percentage35to44
marketindicespopulationdemographicsage_age18plus_percentage45to54
marketindicespopulationdemographicsage_age18plus_percentage55to64
marketindicespopulationdemographicsage_age18plus_percentage65to74
marketindicespopulationdemographicsage_age18plus_percentage75plus
marketindicespopulationdemographicsage_age25plus_averageage
marketindicespopulationdemographicsage_age25plus_medianage
marketindicespopulationdemographicsage_ageblack_percentage18to64
marketindicespopulationdemographicsage_ageblack_percentage65plus
marketindicespopulationdemographicsage_ageblack_percentunderage18
marketindicespopulationdemographicsage_agehispanic_percentage18to64
marketindicespopulationdemographicsage_agehispanic_percentage65plus
marketindicespopulationdemographicsage_agehispanic_percentunderage18
marketindicespopulationdemographicsage_total_averageage
marketindicespopulationdemographicsage_total_medianage
marketindicespopulationdemographicsage_total_percentage18to64
marketindicespopulationdemographicsage_total_percentage65plus
marketindicespopulationdemographicsage_total_percentunderage18
marketindicespopulationdemographicsage_white_percentage18to64
marketindicespopulationdemographicsage_white_percentage65plus
marketindicespopulationdemographicsage_white_percentunderage18
marketindicespopulationdemographicsage_household_underage18_percentage12to14
marketindicespopulationdemographicsage_household_underage18_percentage15to17
marketindicespopulationdemographicsage_household_underage18_percentage3to4
marketindicespopulationdemographicsage_household_underage18_percentage3to5
marketindicespopulationdemographicsage_household_underage18_percentage5
marketindicespopulationdemographicsage_household_underage18_percentage6to11
marketindicespopulationdemographicsage_household_underage18_percentage6to8
marketindicespopulationdemographicsage_household_underage18_percentage9to11
marketindicespopulationdemographicsage_household_underage18_percentunderage3
place_placeid
household_household_id
shoppingandpurchasechannel_mailorderbuyer
shoppingandpurchasechannel_mailorderdonor
shoppingandpurchasechannel_onlinepurchaseindicator
client_id
c360_id
dob
seaware_id

In [117]:
print("row count:",bain.shape)
print("unique surveyid count:", np.unique(bain.surveyid).shape)
print("unique surveyid count:", np.unique(bain.surveygroupid).shape)
#bain_oneper = bain.groupby('id').first()

row count: (740, 326)
unique surveyid count: (616,)
unique surveyid count: (616,)

In [118]:
duplicateRowsDF = bain[bain.duplicated(['surveygroupid'])]
duplicateRowsDF.sort_values('surveygroupid').head()

,surveygroupid,surveyid,sitename,surveydate,userhostaddress,redflag,scored,q126_gender,q127_age,q131_country_of_residence,...,shoppingandpurchasechannel_onlinepurchaseindicator,client_id,crm_id,c360_id,dob,country,seaware_id,master_id,vxp_id,data_loaded_from_nl
537,494094,4267836,Virgin Voyages,58:48.9,173.20.102.108:29348,0,1,Female,47,United States,...,True,30176,0016A00000nQXsGQAW,3.834870e+18,NaN,US,12984,24953ca6-51ac-44b5-9528-1761ec9e09fb,ND in XREF Master,N
261,494098,4267840,Virgin Voyages,59:34.9,207.237.138.42:26233,0,1,Male,43,United States,...,False,24110,0016A00000m8XmpQAE,4.122880e+18,NaN,US,9286,ab14f176-77a9-4a59-afc2-9cee0685c1ac,ND in XREF Master,N
693,494100,4267842,Virgin Voyages,00:08.3,75.166.35.80:51228,0,1,Male,71,United States,...,True,21229,0016A00000nQFGmQAO,4.122830e+18,NaN,US,11943,9e85ce6a-dbd3-4dfa-b054-d69b2bb5b1f1,ND in XREF Master,N
104,494118,4267860,Virgin Voyages,02:28.0,172.58.6.240:46140,0,1,Female,53,United States,...,True,17526,0016A00000m8YfbQAE,7.365190e+18,NaN,US,9306,60b64547-e883-4cae-921e-eec543125e0f,ND in XREF Master,N
105,494118,4267860,Virgin Voyages,02:28.0,172.58.6.240:46140,0,1,Female,53,United States,...,True,29496,0016A00000m8KljQAE,3.544960e+18,NaN,US,8952,5c1904d4-8b43-451d-a0b9-bc7e874cc0d3,ND in XREF Master,N

In [119]:
bain_nodup = bain.drop_duplicates('surveygroupid')
bain_nodup = bain_nodup.drop_duplicates('client_id')
print("row count:",bain_nodup.shape)
print("unique surveyid count:", np.unique(bain_nodup.surveyid).shape)

row count: (612, 326)
unique surveyid count: (612,)

In [120]:
#leaving surveygroupid in
survey_coluns = ["surveyid","sitename","surveydate","userhostaddress","redflag","scored","q126_gender",
                 "q127_age","q131_country_of_residence","q132_zip/postal_code","q128_marital_status",
                 "q129_number_of_children_under_18","q130_annual_household_income","q50_access_url","customer_id",
                 "group_type","q51_access_method","q100","q101","q102","q103","q104","q105","q106","q107","q108","q109",
                 "q110","q111","q112","q113","q114","q115","q116","q117","q118","q119","q120","q121","q122","q123","q124",
                 "q125","q200","assigned_segment","group","id"]

vv_non_acxiom_attributes = ["document_id","client_id","crm_id","c360_id","dob","country","seaware_id","master_id",
                            "vxp_id","data_loaded_from_nl"]

useless_acxiom_attributes = ['person_abilitec_consumerlink', 'place_abilitec_addresslink', 'household_abilitec_householdlink',
                            'place_placeid', 'household_household_id']

bain_acxiom_master = bain_nodup.drop(survey_coluns, axis = 1)
bain_acxiom_master = bain_acxiom_master.drop(vv_non_acxiom_attributes, axis = 1)
bain_acxiom_master = bain_acxiom_master.drop(useless_acxiom_attributes, axis = 1)

In [121]:
bain_acxiom_master_clean = bain_acxiom_master
clean_dfs = []
for i in bain_acxiom_master.columns:
    
    if bain_acxiom_master[i].dtype == bain_acxiom_master['interests_artsandentertainment'].dtypes and i != "surveygroupid":
        l = list(bain_acxiom_master[i].fillna(''))
        l = [[word for word in row.split('|')] for row in l]
        
        prefix = i + "."
        cols=set(prefix + word for row in l  for word in row) #forming a set of distinct text
        if prefix in cols:
            cols.remove(prefix)
        
        new_df=pd.DataFrame(columns=cols)
        for row_idx in range(len(l)):
            for col in cols:
                new_df.loc[row_idx,col]=int(col in prefix + l[row_idx][0])
                
        clean_dfs.append(new_df)
        bain_acxiom_master_clean = bain_acxiom_master_clean.drop([i], axis = 1)

bain_acxiom_master_full = pd.concat(clean_dfs, axis = 1)
bain_acxiom_master_full = pd.concat([bain_acxiom_master_clean, bain_acxiom_master_full], axis = 1)

In [123]:
bain_acxiom_master_full.head()

,surveygroupid,person_basicdemographics_age,person_basicdemographics_deceased,person_basicdemographics_enteringadulthood,person_basicdemographics_lengthofresidence,person_basicdemographics_singleparent,household_basicdemographics_africanamericanprofessionals,household_basicdemographics_childnearhsgraduation,household_basicdemographics_childrenpresent,household_basicdemographics_estimatedincomemin,...,shoppingandpurchasechannel_mailorderbuyercategories.Art & antiques,shoppingandpurchasechannel_mailorderbuyercategories.Outdoor/Hunting & fishing,shoppingandpurchasechannel_mailorderbuyercategories.Beauty,shoppingandpurchasechannel_mailorderbuyercategories.High ticket merchandise,shoppingandpurchasechannel_mailorderbuyercategories.Travel,shoppingandpurchasechannel_mailorderbuyercategories.Food,shoppingandpurchasechannel_mailorderbuyercategories.Jewelry,shoppingandpurchasechannel_mailorderbuyercategories.Auto supplies,shoppingandpurchasechannel_mailorderbuyercategories.Art & crafts,shoppingandpurchasechannel_mailorderbuyercategories.General gifts and merchandise
0,495554.0,60.0,False,False,15.0,True,False,False,True,125000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,494177.0,32.0,False,False,7.0,True,False,False,True,75000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,495191.0,56.0,False,False,15.0,False,False,False,False,125000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,494586.0,44.0,False,False,10.0,True,False,False,True,50000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,494841.0,36.0,False,False,1.0,False,False,False,False,50000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [125]:
bain_acxiom_master_full.to_csv("../data/bain_acxiom_master_full.csv", index = False)