In [2]:
import numpy as np
import pandas as pd

In [4]:
bain_model = pd.read_csv("../../raw/bain_model_table.csv", float_precision='round_trip')
example_responses = pd.read_csv("../../raw/example_responses.csv", float_precision='round_trip')
email_survey_responses = pd.read_csv("../../raw/email_survey_responses.csv", float_precision='round_trip')

In [17]:
bain_model

,Respondent,I always choose higher end hotels,On vacation I pride myself on discovering new places and things my friends have not seen before,I choose more expensive hotels and accommodations to make sure I get the best service and amenities,It is important for me to be in a luxurious setting and to be pampered on vacation,I like to immerse myself in the local culture when on vacation,The difference between luxury and standard hotels just is not big enough to justify the cost,I always pay more for a higher class of room on my vacations,I would rather spend as little as possible on accommodations so I have more money to spend on other parts of my vacation,I think spending more for unique experiences is part of what makes a vacation special,I like to go on vacations that are off the beaten path,Constant
0,Cheap + Comfy,3.480,2.552,2.732,2.225,3.606,4.344,2.230,2.988,3.530,1.874,-41.736
1,Cheap + Curious,2.770,4.190,1.959,1.579,5.185,4.576,1.694,3.588,4.606,2.820,-58.956
2,Curious,4.866,3.886,4.075,3.129,4.859,3.847,3.119,2.907,4.568,2.830,-66.499
3,Comfy,5.229,2.538,4.544,3.857,3.747,3.701,3.786,2.755,3.776,1.939,-57.042
4,Craver,6.956,3.885,5.557,5.598,5.017,4.127,4.806,3.286,4.932,2.628,-96.451
5,Caviar,6.717,3.148,6.001,5.022,4.459,2.815,4.864,1.919,4.444,2.085,-78.828

In [18]:
print(bain_model.to_dict())

{'Respondent': {0: 'Cheap + Comfy', 1: 'Cheap + Curious', 2: 'Curious', 3: 'Comfy', 4: 'Craver', 5: 'Caviar'}, 'I always choose higher end hotels': {0: 3.48, 1: 2.77, 2: 4.866, 3: 5.229, 4: 6.956, 5: 6.717}, 'On vacation I pride myself on discovering new places and things my friends have not seen before': {0: 2.552, 1: 4.19, 2: 3.886, 3: 2.538, 4: 3.885, 5: 3.148}, 'I choose more expensive hotels and accommodations to make sure I get the best service and amenities': {0: 2.732, 1: 1.959, 2: 4.075, 3: 4.544, 4: 5.557, 5: 6.001}, 'It is important for me to be in a luxurious setting and to be pampered on vacation': {0: 2.225, 1: 1.579, 2: 3.129, 3: 3.857, 4: 5.598, 5: 5.022}, 'I like to immerse myself in the local culture when on vacation': {0: 3.606, 1: 5.185, 2: 4.859, 3: 3.747, 4: 5.017, 5: 4.459}, 'The difference between luxury and standard hotels just is not big enough to justify the cost': {0: 4.344, 1: 4.576, 2: 3.847, 3: 3.701, 4: 4.127, 5: 2.815}, 'I always pay more for a higher class of room on my vacations': {0: 2.23, 1: 1.694, 2: 3.119, 3: 3.786, 4: 4.806, 5: 4.864}, 'I would rather spend as little as possible on accommodations so I have more money to spend on other parts of my vacation': {0: 2.988, 1: 3.588, 2: 2.907, 3: 2.755, 4: 3.286, 5: 1.919}, 'I think spending more for unique experiences is part of what makes a vacation special': {0: 3.53, 1: 4.606, 2: 4.568, 3: 3.776, 4: 4.932, 5: 4.444}, 'I like to go on vacations that are off the beaten path': {0: 1.874, 1: 2.82, 2: 2.83, 3: 1.939, 4: 2.628, 5: 2.085}, 'Constant': {0: -41.736, 1: -58.956, 2: -66.499, 3: -57.042, 4: -96.451, 5: -78.828}}

In [9]:
bain_model2 = {'Respondent': {0: 'Cheap + Comfy', 1: 'Cheap + Curious', 2: 'Curious', 3: 'Comfy', 4: 'Craver', 5: 'Caviar'}, 'I always choose higher end hotels': {0: 3.48, 1: 2.77, 2: 4.866, 3: 5.229, 4: 6.956, 5: 6.717}, 'On vacation I pride myself on discovering new places and things my friends have not seen before': {0: 2.552, 1: 4.19, 2: 3.886, 3: 2.538, 4: 3.885, 5: 3.148}, 'I choose more expensive hotels and accommodations to make sure I get the best service and amenities': {0: 2.732, 1: 1.959, 2: 4.075, 3: 4.544, 4: 5.557, 5: 6.001}, 'It is important for me to be in a luxurious setting and to be pampered on vacation': {0: 2.225, 1: 1.579, 2: 3.129, 3: 3.857, 4: 5.598, 5: 5.022}, 'I like to immerse myself in the local culture when on vacation': {0: 3.606, 1: 5.185, 2: 4.859, 3: 3.747, 4: 5.017, 5: 4.459}, 'The difference between luxury and standard hotels just is not big enough to justify the cost': {0: 4.344, 1: 4.576, 2: 3.847, 3: 3.701, 4: 4.127, 5: 2.815}, 'I always pay more for a higher class of room on my vacations': {0: 2.23, 1: 1.694, 2: 3.119, 3: 3.786, 4: 4.806, 5: 4.864}, 'I would rather spend as little as possible on accommodations so I have more money to spend on other parts of my vacation': {0: 2.988, 1: 3.588, 2: 2.907, 3: 2.755, 4: 3.286, 5: 1.919}, 'I think spending more for unique experiences is part of what makes a vacation special': {0: 3.53, 1: 4.606, 2: 4.568, 3: 3.776, 4: 4.932, 5: 4.444}, 'I like to go on vacations that are off the beaten path': {0: 1.874, 1: 2.82, 2: 2.83, 3: 1.939, 4: 2.628, 5: 2.085}, 'Constant': {0: -41.736, 1: -58.956, 2: -66.499, 3: -57.042, 4: -96.451, 5: -78.828}}
pd.DataFrame.from_dict(bain_model2)

,Respondent,I always choose higher end hotels,On vacation I pride myself on discovering new places and things my friends have not seen before,I choose more expensive hotels and accommodations to make sure I get the best service and amenities,It is important for me to be in a luxurious setting and to be pampered on vacation,I like to immerse myself in the local culture when on vacation,The difference between luxury and standard hotels just is not big enough to justify the cost,I always pay more for a higher class of room on my vacations,I would rather spend as little as possible on accommodations so I have more money to spend on other parts of my vacation,I think spending more for unique experiences is part of what makes a vacation special,I like to go on vacations that are off the beaten path,Constant
0,Cheap + Comfy,3.480,2.552,2.732,2.225,3.606,4.344,2.230,2.988,3.530,1.874,-41.736
1,Cheap + Curious,2.770,4.190,1.959,1.579,5.185,4.576,1.694,3.588,4.606,2.820,-58.956
2,Curious,4.866,3.886,4.075,3.129,4.859,3.847,3.119,2.907,4.568,2.830,-66.499
3,Comfy,5.229,2.538,4.544,3.857,3.747,3.701,3.786,2.755,3.776,1.939,-57.042
4,Craver,6.956,3.885,5.557,5.598,5.017,4.127,4.806,3.286,4.932,2.628,-96.451
5,Caviar,6.717,3.148,6.001,5.022,4.459,2.815,4.864,1.919,4.444,2.085,-78.828

In [17]:
np.intersect1d(bain_model.columns, bain_model.columns).shape[0]

12

In [24]:
%%writefile ../../progs/bain_response_enrich.py
def bain_response_enrich(res):
    """
    Requires: numpy, pandas
    Purpose: Enrich a dataframe of responses to the Bain Survey questions with model values and a resulting Bain Segment
    Input: 
        - res: A dataframe of responses to Bain Survey quesitons with the following columns:
            + 'UID'
            + 'I always choose higher end hotels'
            + 'On vacation I pride myself on discovering new places and things my friends have not seen before'
            + 'I choose more expensive hotels and accommodations to make sure I get the best service and amenities'
            + 'It is important for me to be in a luxurious setting and to be pampered on vacation'
            + 'I like to immerse myself in the local culture when on vacation'
            + 'The difference between luxury and standard hotels just is not big enough to justify the cost'
            + 'I always pay more for a higher class of room on my vacations'
            + 'I would rather spend as little as possible on accommodations so I have more money to spend on other parts of my vacation'
            + 'I think spending more for unique experiences is part of what makes a vacation special'
            + 'I like to go on vacations that are off the beaten path'
    Output: 
        - res: An enriched res dataframe with added columns:
            + One column per Bain segment, where each value is the resulting value of the regression model
            + 'Assigned Segment': The assigned segment is the segment which has the maximum resulting regression value
            + 'Assigned Segment (Model Value)': The maximum model value which was used to assign the segment
    """
    #Libarary load
    import numpy as np
    import pandas as pd
    
    #Bain model - hardcoded from past Bain research
    #- mod: A dataframe of the Bain model table, which includes:
    #        + Columns for the Survey Questions from res, 
    #        + Constant column
    #        + One row per segment, the segment choices are:
    #            * 'Cheap + Comfy'
    #            * 'Cheap + Curious'
    #            * 'Curious'
    #            * 'Comfy'
    #            * 'Craver'
    #            * 'Caviar'
    
    mod = pd.DataFrame.from_dict({
           'Respondent': {0: 'Cheap + Comfy', 1: 'Cheap + Curious', 2: 'Curious', 3: 'Comfy', 4: 'Craver', 5: 'Caviar'}, 
           'I always choose higher end hotels': {0: 3.48, 1: 2.77, 2: 4.866, 3: 5.229, 4: 6.956, 5: 6.717}, 
           'On vacation I pride myself on discovering new places and things my friends have not seen before': {0: 2.552, 1: 4.19, 2: 3.886, 3: 2.538, 4: 3.885, 5: 3.148}, 
           'I choose more expensive hotels and accommodations to make sure I get the best service and amenities': {0: 2.732, 1: 1.959, 2: 4.075, 3: 4.544, 4: 5.557, 5: 6.001}, 
           'It is important for me to be in a luxurious setting and to be pampered on vacation': {0: 2.225, 1: 1.579, 2: 3.129, 3: 3.857, 4: 5.598, 5: 5.022}, 
           'I like to immerse myself in the local culture when on vacation': {0: 3.606, 1: 5.185, 2: 4.859, 3: 3.747, 4: 5.017, 5: 4.459}, 
           'The difference between luxury and standard hotels just is not big enough to justify the cost': {0: 4.344, 1: 4.576, 2: 3.847, 3: 3.701, 4: 4.127, 5: 2.815}, 
           'I always pay more for a higher class of room on my vacations': {0: 2.23, 1: 1.694, 2: 3.119, 3: 3.786, 4: 4.806, 5: 4.864}, 
           'I would rather spend as little as possible on accommodations so I have more money to spend on other parts of my vacation': {0: 2.988, 1: 3.588, 2: 2.907, 3: 2.755, 4: 3.286, 5: 1.919}, 
           'I think spending more for unique experiences is part of what makes a vacation special': {0: 3.53, 1: 4.606, 2: 4.568, 3: 3.776, 4: 4.932, 5: 4.444}, 
           'I like to go on vacations that are off the beaten path': {0: 1.874, 1: 2.82, 2: 2.83, 3: 1.939, 4: 2.628, 5: 2.085}, 
           'Constant': {0: -41.736, 1: -58.956, 2: -66.499, 3: -57.042, 4: -96.451, 5: -78.828}
    })
    
    #Input Validations
    #10 Survey questions must be *exactly* the same in response and model DFs
    if np.intersect1d(mod.columns, res.columns).shape[0] == 12: 
        raise Exception("The 10 Survey questions must be *exactly* the same in the res and mod DFs.")
    
    
    #Helper function
    def value_extract(mod, col, seg):
        """
        Purpose: Extract a single cell coefficient from the model table, based on question and segment
        Input: 
            - mod: Model table
            - col: Column in model table (question)
            - seg: Bain segment
        Output: Single cell coefficient from the model table
        """
        return mod[col][mod["Respondent"]==seg].reset_index(drop=True)[0]

    #Temp assignment (values will be overriden)
    res.loc[:,'Assigned Segment'] = ""
    res.loc[:,'Assigned Segment (Model Value)'] = 0
    
    #Main loop
    #Loop through Bain Segments
    for i in mod.Respondent:
        res.loc[:,i] = value_extract(mod, 'Constant', i)
        
        #Loop through Bain survey questions
        for a in mod.columns[1:11]:
            res.loc[:,i] = res.loc[:,i] + (value_extract(mod, a, i) * res[a])

        #Assign segment if resulting model value is the maximum resulting value
        res.loc[:,'Assigned Segment'] = np.where(
            res['Assigned Segment (Model Value)'] >= res[i], res['Assigned Segment'], i)
        res.loc[:,'Assigned Segment (Model Value)'] = np.where(
            res['Assigned Segment'] == i, res[i], res['Assigned Segment (Model Value)'])
    
    #Return the enriched res dataframe
    return res

Overwriting ../../progs/bain_response_enrich.py

In [20]:
bain_response_enrich(example_responses)

,UID,I always choose higher end hotels,On vacation I pride myself on discovering new places and things my friends have not seen before,I choose more expensive hotels and accommodations to make sure I get the best service and amenities,It is important for me to be in a luxurious setting and to be pampered on vacation,I like to immerse myself in the local culture when on vacation,The difference between luxury and standard hotels just is not big enough to justify the cost,I always pay more for a higher class of room on my vacations,I would rather spend as little as possible on accommodations so I have more money to spend on other parts of my vacation,I think spending more for unique experiences is part of what makes a vacation special,I like to go on vacations that are off the beaten path,Assigned Segment,Assigned Segment (Model Value),Cheap + Comfy,Cheap + Curious,Curious,Comfy,Craver,Caviar
0,1,5,5,5,2,4,5,1,5,3,4,Curious,85.243,77.934,77.149,85.243,82.365,83.982,78.588
1,2,1,5,2,1,5,5,2,4,4,5,Cheap + Curious,69.330,61.845,69.330,62.894,54.453,47.986,42.628
2,3,3,5,3,3,5,3,3,5,5,5,Curious,85.859,76.047,80.723,85.859,80.084,83.421,77.704
3,4,3,3,3,3,3,3,3,3,3,3,Comfy,50.574,46.947,39.945,47.759,50.574,43.925,45.594
4,5,5,5,5,5,5,5,5,5,5,5,Craver,137.509,106.069,105.879,123.931,122.318,137.509,128.542
5,6,5,2,5,5,2,1,5,1,5,3,Caviar,82.615,54.519,39.458,65.020,73.761,75.895,82.615

In [21]:
bain_response_enrich(example_responses.rename(columns={"I always choose higher end hotels": "WRONG QUESTION"}))

Exception: The 10 Survey questions must be *exactly* the same in the res and mod DFs.

In [31]:
email_survey_responses.head()

,Respondent,Assigned Segment,I always choose higher end hotels,On vacation I pride myself on discovering new places and things my friends have not seen before,I choose more expensive hotels and accommodations to make sure I get the best service and amenities,It is important for me to be in a luxurious setting and to be pampered on vacation,I like to immerse myself in the local culture when on vacation,The difference between luxury and standard hotels just is not big enough to justify the cost,I always pay more for a higher class of room on my vacations,I would rather spend as little as possible on accommodations so I have more money to spend on other parts of my vacation,I think spending more for unique experiences is part of what makes a vacation special,I like to go on vacations that are off the beaten path,Cheap + Comfy,Cheap + Curious,Curious,Comfy,Craver,Caviar
0,496367,Curious,1,5,3,3,5,2,1,1,3,2,35.65,35.19,36.79,33.97,24.88,28.91
1,496360,Comfy,3,3,3,3,4,4,2,4,2,3,52.12,46.99,51.69,53.22,46.62,45.48
2,496350,Caviar,5,5,5,5,5,1,5,1,5,5,76.74,73.22,96.91,96.50,107.86,109.61
3,496339,Cheap + Comfy,2,3,2,3,4,4,2,3,3,4,48.33,46.10,47.23,46.41,38.38,37.37
4,496333,Curious,3,5,3,2,5,3,2,3,3,4,56.68,58.24,61.83,57.45,53.95,53.01

In [33]:
input_res = email_survey_responses.drop(['Assigned Segment','Cheap + Comfy', 'Cheap + Curious', 'Curious', 'Comfy', 'Craver','Caviar'], 
                            axis=1)
input_res = bain_response_enrich(input_res)

print("# of assigned segments different:",np.sum(input_res['Assigned Segment'] != email_survey_responses['Assigned Segment']))
input_res[input_res['Assigned Segment'] != email_survey_responses['Assigned Segment']]

# of assigned segments different: 1

,Respondent,I always choose higher end hotels,On vacation I pride myself on discovering new places and things my friends have not seen before,I choose more expensive hotels and accommodations to make sure I get the best service and amenities,It is important for me to be in a luxurious setting and to be pampered on vacation,I like to immerse myself in the local culture when on vacation,The difference between luxury and standard hotels just is not big enough to justify the cost,I always pay more for a higher class of room on my vacations,I would rather spend as little as possible on accommodations so I have more money to spend on other parts of my vacation,I think spending more for unique experiences is part of what makes a vacation special,I like to go on vacations that are off the beaten path,Assigned Segment,Assigned Segment (Model Value),Cheap + Comfy,Cheap + Curious,Curious,Comfy,Craver,Caviar
825,494420,2,4,3,4,3,3,3,4,4,4,Curious,60.213,56.636,53.958,60.213,60.21,57.298,55.495

In [34]:
i = input_res[['Cheap + Comfy', 'Cheap + Curious', 'Curious', 'Comfy', 'Craver','Caviar']].values

In [35]:
e = email_survey_responses[['Cheap + Comfy', 'Cheap + Curious', 'Curious', 'Comfy', 'Craver','Caviar']].values

In [36]:
print("max diff:", np.max(np.round(i - e,3)))
print("min diff:", np.min(np.round(i - e,3)))

max diff: 0.009
min diff: -0.015